review polish change
awxiaoxian2020/pinia pull request #1
Opened 2022-10-19 15:00 UTC by KimYangOfCat

2022-10-19 23:50 UTC, awxiaoxian2020 requested changes

2022-10-19 23:50 UTC, awxiaoxian2020 commented on packages/docs/zh/core-concepts/plugins.md
> +如果你使用的是**Vue 2**，Pinia 与 Vue 一样，受限于[相同的响应式限制](https://v2.cn.vuejs.org/v2/guide/reactivity.html#检测变化的注意事项)。在创建新的 state 属性时,如 `secret` 和 `hasError`，你需要使用 `Vue.set()` (Vue 2.7) 或者 `@vue/composition-api`
```suggestion
如果你使用的是 **Vue 2**，Pinia 与 Vue 一样，受限于[相同的响应式限制](https://v2.cn.vuejs.org/v2/guide/reactivity.html#检测变化的注意事项)。在创建新的 state 属性时,如 `secret` 和 `hasError`，你需要使用 `Vue.set()` (Vue 2.7) 或者 `@vue/composition-api` 的 `set()` (Vue < 2.7)。
```

2022-10-23 22:49 UTC, awxiaoxian2020 requested changes

2022-10-23 22:49 UTC, awxiaoxian2020 commented on packages/docs/zh/cookbook/migration-vuex.md
> +如果你以前使用的是 Vuex 的 `map` 辅助函数，可以看看[不使用 setup() 的用法指南](./options-api.md)，因为这些辅助函数大多都是可以复用。
```suggestion
如果你以前使用的是 Vuex 的 `map` 辅助函数，可以看看[不使用 setup() 的用法指南](./options-api.md)，因为这些辅助函数大多都是可以复用的。
```

2022-10-23 22:56 UTC, awxiaoxian2020 requested changes

2022-10-23 22:56 UTC, awxiaoxian2020 commented on packages/docs/zh/core-concepts/actions.md
> +Action 相当于组件中的 [method](https://v3.vuejs.org/guide/data-methods.html#methods)。它们可以通过 `defineStore()` 中的 `actions` 属性来定义，**并且它们也是定义业务逻辑的完美选择。**
虽然上次我们讨论的时候提到，是不是统一单数会比较好。虽然 Vue 翻译指南也是这样写的，但是你也说了，要根据具体情况而定，这里的 Actions 是不是对应下面的 `actions` 的属性，所以保留复数会比较好呢？

2022-10-23 23:10 UTC, awxiaoxian2020 requested changes

2022-10-23 23:10 UTC, awxiaoxian2020 commented on packages/docs/zh/api/modules/pinia.md
> +除了创建的计算属性的 stter，其他与 `mapState()` 相同，
```suggestion
除了创建的计算属性的 setter，其他与 `mapState()` 相同，
```

2022-10-24 01:16 UTC, KimYangOfCat commented on packages/docs/zh/core-concepts/actions.md
> +Action 相当于组件中的 [method](https://v3.vuejs.org/guide/data-methods.html#methods)。它们可以通过 `defineStore()` 中的 `actions` 属性来定义，**并且它们也是定义业务逻辑的完美选择。**
你说的没错，这里 Action 确实对应下面的 actions 属性，但这里我个人认为它的含义是 Action 是 pinia 提供的一个功能特性，而这个功能特性是需要通过 actions 这个属性定义的，但我认为在这个语境中它们并不一指代同一实体，所以没有必要保持单复数一致，且 Action 为单数更能体现一个功能特性的含意。

相反，如果你把 Actions 理解为具象的每一个定义的 action 操作，那保持复数也没有关系。

目前我个人偏好作为一个功能特性来理解，毕竟这一部分是写在核心概念章节中专门介绍 Action 的部分。Getter 与 State 我也是想似的理解思路，所以也保持了单数

2022-10-24 14:25 UTC, KimYangOfCat commented
PTAL

2022-10-25 00:18 UTC, awxiaoxian2020 commented
> PTAL

I will review it these days.

2022-10-25 01:26 UTC, awxiaoxian2020 approved these changes

2022-10-25 01:26 UTC, merged